name: data_check
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.0
  - pandas=2.3.2
  - pytest=8.4.2
  - scipy=1.16.2
  - pip=24.3.1
  - pip:
      - mlflow==3.4.0
      - wandb==0.22.0
